# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 60
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: |
      conda create --yes --name pdal -c conda-forge pdal pytest numpy compilers
    displayName: 'Dependencies'
  - script: |
      activate pdal
      pip install  .
    displayName: 'Build'
  - script: |
      activate pdal
      python -m pytest
    displayName: 'Test'
