# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.13
  timeoutInMinutes: 360
  steps:
  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - script: |
      ECHO ON
      source activate base
      conda create --yes --quiet --name pdal
    displayName: Create conda environment

  - script: |
      ECHO ON
      source activate pdal
      conda config --set always_yes True --set show_channel_urls True
      conda install --yes --quiet --name pdal -c conda-forge  cython packaging pdal conda-forge-ci-setup=2 -y
    displayName: Install PDAL
  - script: |
      source activate pdal
      export CI=azure
      source run_conda_forge_build_setup
      env: {
        OSX_FORCE_SDK_DOWNLOAD: "1"
      }
    displayName: Configure OSX SDK
  - script: |
      source activate pdal
      pip install numpy packaging cython
    displayName: 'Dependencies'
  - script: |
      python setup.py build
    displayName: 'Build'
  - script: |
      python setup.py test
    displayName: 'Test'

