
jobs:
- job: win

  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 360
  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    - script: |
        ECHO ON
        call conda update -n base -c defaults conda
        call conda create --yes --quiet --name pdal
      displayName: Create conda environment

    - script: |
        ECHO ON
        call activate pdal
        call conda config --set always_yes True --set show_channel_urls True
        call conda install --yes --quiet --name pdal -c conda-forge  compilers pdal pytest -y
      displayName: Install PDAL
    - script: |
        ECHO ON
        call activate pdal
        pip install .
      displayName: 'Build'
    - script: |
        call activate pdal
        py.test
      displayName: 'Test'


