
jobs:
- job: win

  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 360
  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH
    - script: |
        rmdir C:\strawberry /s /q
      continueOnError: true
      displayName: remove strawberryperl
    - script: |
        ECHO ON
        call conda update -n base -c defaults conda
        call conda create --yes --quiet --name pdal
      displayName: Create conda environment

    - script: |
        ECHO ON
        call activate pdal
        call conda config --set always_yes True --set show_channel_urls True
        call conda install --yes --quiet --name pdal -c conda-forge scikit-build compilers  ninja pdal pytest conda-build -y
      displayName: Install PDAL
    - script: |
        ECHO ON
        call activate pdal
        ninja -h
        msbuild /verbosity:diag
        set VCTargetsPath="C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\""
        #pip install -e .  --install-option="--skip-generator-test --generator=Ninja"
        pip install -e .
        # --install-option="-DPdal_DIR=%CONDA_PREFIX%\Library\lib\cmake\PDAL"
      displayName: 'Build'
    - script: |
        call activate pdal
        py.test
      displayName: 'Test'


