
jobs:
- job: win

  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 360
  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    - script: |
        ECHO ON
        call conda create --yes --quiet --name pdal
      displayName: Create conda environment

    - script: |
        ECHO ON
        call activate pdal
        call conda config --set always_yes True --set show_channel_urls True
        call conda install --yes --quiet --name pdal -c conda-forge  pdal -y
      displayName: Install PDAL
    - script: |
        ECHO ON
        call activate pdal
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        echo %PATH%
        set CC=cl.exe
        set CXX=cl.exe
        # . --install-option="-DPdal_DIR=%CONDA_PREFIX%\Library\lib\cmake\PDAL"
        pip install .
      displayName: 'Build'
    - script: |
        ECHO ON
        call activate pdal
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        set PYTHONHOME=%CONDA_PREFIX%
        py.test
      displayName: 'Test'


