# .travis.yml
# Configure Travis CI service for http://github.com/PDAL/python

sudo: required

services: docker

before_install:
  - docker pull pdal/pdal:master

script:
  - docker run -v $TRAVIS_BUILD_DIR:/pdal -t pdal/pdal:master /bin/sh -c "/pdal/scripts/travis/script.sh"

